---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.repo }}-ecr-renewal
  namespace: {{ .Values.repo }}-development
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.repo }}-ecr-renew
  namespace: {{ .Values.repo }}-development
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.repo }}-ecr-renew
  namespace: {{ .Values.repo }}-ci-cd
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.repo }}-ecr-renew-binding
  namespace: {{ .Values.repo }}-development
subjects:
- kind: ServiceAccount
  name: {{ .Values.repo }}-ecr-renewal
  namespace: {{ .Values.repo }}-development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.repo }}-ecr-renew
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.repo }}-ecr-renew-binding
  namespace: {{ .Values.repo }}-ci-cd
subjects:
- kind: ServiceAccount
  name: {{ .Values.repo }}-ecr-renewal
  namespace: {{ .Values.repo }}-development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.repo }}-ecr-renew