# The secret github-private-key is generated under the each/depdendencies
# It's executed via  TaskRun called create-github-resources
# It generates a ssh private key and adds to the repository
# Also saves under the ci-cd namespace with the github-privatey-key name
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: {{ .Values.repo }}-ci-cd
secrets:
  - name: github-private-key
  # - name: github-{{ .Values.repo }}-https-auth
  # - name: github-{{ .Values.repo }}-gitops-ssh
imagePullSecrets:
- name: regcred