apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-aws-ecr-registry
  namespace: tekton-tasks
spec:
  description: |
    Creates a new AWS ECR registry for a new discovered service if the registry doesn't exist already
  params:
    - name: repo-name
      description: repository to be created
    - name: region
      description: aws region to create the registry
      default: us-east-1

  steps:
    - name: create-webhook
      image: xynova/aws-kubectl:latest
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
      script: |
        #!/bin/sh
        aws ecr describe-repositories --repository-names "$(params.repo-name)" --region "$(params.region)" >/dev/null 2>&1 || aws ecr create-repository --repository-name "$(params.repo-name)" --region "$(params.region)"
