---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-deployment
  namespace: tekton-tasks
spec:
  description: this is a task to verify the deployment after the deployment.
  params:
    - name: revision_type
      description: type of branch
    - name: application_name
      description: Application name
      type: string
    - name: repository
      description: Github repository
    - name: truncated_sha
      description: Version of currently running app
  steps:
    - name: verify
      image: bitnami/kubectl
      script: |
        #!/bin/sh
        if [ "$(params.revision_type)" = "main" ]; then
          until [ "$label" = "$(params.truncated_sha)" ]; do
            echo "Revision $(params.truncated_sha) hasn't started to roll out yet"
            label=$(kubectl get deployment/$(params.application_name) -n $(params.repository)-development --template='{{ index .metadata.labels "app.version" }}')
            sleep 1
          done          

          kubectl rollout status --timeout=2m deployment/$(params.application_name) -n $(params.repository)-development || rc1=$?
          if [[ $ROLLOUT_FAIL != '' ]]; then
            echo "Rollout failed. Rollback"
          else
            echo "No rollback required 🎉🎉🎉"
          fi
        else
          echo "Skipping due to not being in main branch"
        fi
