---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: "set-backstage-groups"
  namespace: {{ .Values.repo }}-ci-cd
  annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  serviceAccountName: default
  workspaces:
  - name: ssh-directory
    secret:
      secretName: git-credentials-envs
  taskRef:
    resolver: cluster
    params:
    - name: kind
      value: task
    - name: name
      value: create-backstage-entity
    - name: namespace
      value: tekton-tasks
  params:
  - name: kind
    value: Group
  - name: name
    value: {{ .Values.team }}
  - name: repository
    value: git@github.com:dx-book/environments.git
  - name: path
    value: entities
  - name: type
    value: team
  