{{ if .Values.include_apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: generators
  namespace: {{ include "argocd" . }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ include "argocd" . }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: chart/templates/gene
    repoURL: https://github.com/dx-book/platform
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
  ignoreDifferences:
    - group: ''
      kind: Namespace
      jsonPointers:
        - /metadata/annotations
{{- end }}