---
apiVersion: v1
kind: Secret
metadata:
  name: github-environments
  namespace: {{ include "argocd" . }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/dx-book/environments
  password: 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
  username: not-used