apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: tools
  namespace: {{ include "argocd" . }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ include "argocd" . }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/setup/templates/tools/vanilla
    repoURL: https://github.com/moonpod/environment
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - ServerSideApply=true
      - CreateNamespace=true