# Secret to manage AWS ECR
# This is a secret with minimal permissions, only needed to interact with AWS ECR
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: {{ .Values.repo }}-ci-cd
type: Opaque
stringData:
  credentials: |-
    [default]
    aws_access_key_id = {{ .Values.aws.secret.AWS_ACCESS_KEY_ID }}
    aws_secret_access_key = {{ .Values.aws.secret.AWS_SECRET_ACCESS_KEY }}