---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.repo }}-aws-secret
  namespace: {{ .Values.repo }}-development
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: AKIAUICYRSPXR4D73H52
  AWS_SECRET_ACCESS_KEY: 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