apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pipelines
spec:
  generators:
    - matrix:
        generators:
          - scmProvider:
              filters:
                - pathsExist:
                    [chart/Chart.yaml, pipeline/Chart.yaml, Dockerfile]
              github:
                organization: dx-book
                allBranches: false
                tokenRef:
                  secretName: github-environments
                  key: password
          - git:
              repoURL: https://github.com/{{ .Values.org }}/environments.git
              revision: main
              files:
                - path: "applications/{{`{{ repository }}`}}.yaml"
  template:
    metadata:
      name: "tkn-{{`{{ repository }}`}}"
      namespace: argocd
    spec:
      project: default
      source:
        helm:
          releaseName: "tkn-{{`{{ repository }}-{{ info.name }}`}}"
          values: |
            domain: {{ .Values.domain }}
            org: "{{ .Values.org }}"
            repo: "{{`{{ repository }}`}}"
            team: "{{`{{ info.team }}`}}"
            name: "{{`{{ info.name }}`}}"
            aws: 
              account: "{{ .Values.aws.account }}"
              region: "{{ .Values.aws.region }}"
            values: |
              {{`{{ info.values }}`}}
        repoURL: https://github.com/{{ .Values.org }}/{{`{{ repository }}`}}
        targetRevision: main
        path: pipeline
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{`{{ repository }}`}}-ci-cd"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - Validate=true
          - CreateNamespace=false
          - ApplyOutOfSyncOnly=false
