---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.project }}-{{ .Release.Name }}
  namespace: {{ .Values.project }}-ci-cd
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: dev.moonpod.app
    http:
      paths:
      - backend:
          service:
            name: el-{{ .Release.Name }}
            port:
              number: 8080
        path: /github/{{ .Values.project }}/{{ .Values.application.name }}/webhook
        pathType: Exact
  tls:
  - hosts:
    - dev.moonpod.app
    secretName: dev.moonpod.app-tls