---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: ArgoCD project for the tools managed by the platform
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dependencies
  namespace: argocd
spec:
  description: Argo CD project for all teams dependencies
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "https://github.com/dx-book/*"
    - "http://chartmuseum.platform.svc.cluster.local:8080/"
  clusterResourceWhitelist:
    - group: ""
      kind: "Namespace"
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pipelines
  namespace: argocd
spec:
  description: Argo CD project for all teams pipelines
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "https://github.com/dx-book/*"
    - "http://chartmuseum.platform.svc.cluster.local:8080/"
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: Argo CD project for all teams dependencies
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "https://github.com/dx-book/*"
    - "http://chartmuseum.platform.svc.cluster.local:8080/"
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
