---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-manage-argocd-applications
  namespace: {{ .Values.repo }}-ci-cd
subjects:
- kind: ServiceAccount
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-argocd-applications
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: {{ .Values.repo }}-manage-argocd-applications
#   namespace: argocd
# subjects:
# - kind: ServiceAccount
#   name: pipeline
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: manage-argocd-applications