---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-manage-tekton-triggers
  namespace: {{ .Values.repo }}-ci-cd
subjects:
- kind: ServiceAccount
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-tekton-triggers
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-tekton-triggers
  namespace: {{ .Values.repo }}-ci-cd
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - "*"
  verbs:
  - create
  - list
  - get
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - list
  - get
  - watch