---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-manage-secrets
  namespace: {{ .Values.repo }}-ci-cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-secrets
subjects:
- kind: ServiceAccount
  name: github-admin
  namespace: {{ include "argocd" . }}