---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-eventlistener-clusterbinding
  namespace: {{ .Values.repo }}-ci-cd
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.repo }}-ci-cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
