apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project }}-{{ .Values.application.name }}-docker-credentials
  namespace: {{ .Values.project }}-ci-cd
data:
  config.json: {{ .Values.application.dockercfg }}
  