---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.project }}-{{ .Values.application.name }}-ssh-credentials
  namespace: {{ .Values.project }}-ci-cd
data:
  id_rsa: {{ .Values.application.id_rsa }}