---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-secrets
  namespace: {{ include "argocd" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - list
  - get
  - watch
  - patch