---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-argocd-applications
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - get
      - watch

  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - create
      - list
      - get
      - delete
      - watch
      - patch

  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - list
      - get
      - watch
