---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
      - get
      - watch
      - patch
