---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.repo }}-ci-cd
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.repo }}-development
---
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.repo }}-ci-cd
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.repo }}-prod
