apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ include "namespace" . }}
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.3.8
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: true
          password: nfp7kzf8NTH!cga0keknfp7kzf8NTH!cga0keknfp7kzf8NTH!cga0kek
        master:
          containerSecurityContext:
            enabled: false
          podSecurityContext: 
            enabled: false
          persistence:
            enabled: false
        replica:
          containerSecurityContext:
            enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
    