---
apiVersion: v1
kind: Secret
metadata:
  name: github-platform
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/{{ .Values.org }}/platform
  password: {{ .Values.github.secrets.repositories }}
  username: not-used
