# This secret have the credentials to interact with GitHub API for creating webhooks, for example
---
apiVersion: v1
kind: Secret
metadata:
  name: github-admin-auth
  namespace: {{ include "argocd" . }}
type: Opaque
stringData:
  GITHUB_CREDENTIALS: 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